### ISSUE TITLE
unknown fields in module: help

### ISSUE THREAD

**Issue by RubenN** [ninoabbate/docker-secg#1]
Trying to use your docker container, but snmp_exporter gives me the 'unknown fields in module: help' error.

**Edit: After replacing the snmp_exporter with the latest version all is OK**

**Comment by ninoabbate** [comment]
Hi @RubenN, they changed the code to include that module in the latest builds, I had to rebuild the container to fix this. Keep in mind that, as a common rule, the generator and snmp_exporter must match their version, you can find in my dockerhub repo a container for each build, so the container `latest` is equal to the container tagged `v0.6.0`

**Comment by ninoabbate** [comment]
Closing this issue since it is resolved.
